#!/bin/bash
ECHO=/bin/echo
EE=/usr/local/bin/ee
GREP=/bin/grep
CUT=/usr/bin/cut
MKDIR=/bin/mkdir
CAT=/bin/cat
DATE=/bin/date
TAR=/bin/tar
RM=/bin/rm
LS=/bin/ls
SED=/bin/sed
MYSQLDUMP=/usr/bin/mysqldump
MYSQL=/usr/bin/mysql
WC=/usr/bin/wc

if [ "$#" -le 1 ];then
	$ECHO "Usage: $0 <backup/restore> <sitename> [option]"
elif [ "$1" == "backup" ];then
	SITENAME=$2
	BASE_FOLDER=$($EE site info $SITENAME | $GREP Webroot | $CUT -d" " -f2)
	if [ -z "$BASE_FOLDER" ]; then
		$ECHO "Website not found"
	else
		BACKUP_FILENAME=$($DATE +"backup-$SITENAME-%Y%m%d-%H%M.tar.gz")
		if [ ! -d "$BASE_FOLDER/site-backup" ];then
			$MKDIR $BASE_FOLDER/site-backup
		fi
		WPCHECK=$($EE site info $SITENAME | $GREP ^Nginx | $GREP wp | $WC -l)
                MYSQLCHECK=$($EE site info $SITENAME | $GREP ^Nginx | $GREP mysql | $WC -l)
                if [[ $WPCHECK -eq 1 ]] || [[ $MYSQLCHECK -eq 1 ]]; then
                	WPDBNAME=$($EE site info $SITENAME | $GREP DB_NAME | $CUT -d" " -f 2)
                        WPDBUSER=$($EE site info $SITENAME | $GREP DB_USER | $CUT -d" " -f 2)
                        WPDBPASS=$($EE site info $SITENAME | $GREP DB_PASS | $CUT -d" " -f 2)
                        $ECHO -n "Dumping database... "
			$MYSQLDUMP --single-transaction -u$WPDBUSER -p$WPDBPASS $WPDBNAME > $BASE_FOLDER/$WPDBNAME-dump.sql
			$ECHO "[Done]"
			$ECHO -n "Archiving website folder... "
			$TAR -czf $BASE_FOLDER/site-backup/$BACKUP_FILENAME -C $BASE_FOLDER htdocs $WPDBNAME-dump.sql
			$ECHO "[Done]"
			$ECHO -n "Cleaning up... "
			$RM $BASE_FOLDER/$WPDBNAME-dump.sql
			$ECHO "[Done]"
		else
			$ECHO -n "Archiving website folder... "
			$TAR -czf $BASE_FOLDER/site-backup/$BACKUP_FILENAME -C $BASE_FOLDER htdocs
			$ECHO "[Done]"
		fi
	fi
elif [ "$1" == "restore" ];then
	SITENAME=$2
	BASE_FOLDER=$($EE site info $SITENAME | $GREP Webroot | $CUT -d" " -f2)
	if [ -z "$BASE_FOLDER" ]; then
		$ECHO "Website not found"
	else
		if [ -z "$3" ];then
			if [[ ! -d "$BASE_FOLDER/site-backup" || -z $(ls $BASE_FOLDER/site-backup) ]]; then
				$ECHO "No backup found"
			else
				$ECHO "Select which backup to restore:"
				$LS $BASE_FOLDER/site-backup | $SED 's/.tar.gz//'
			fi
		else
			BACKUP_FILENAME=$BASE_FOLDER/site-backup/$3.tar.gz
			if [[ ! -r $BACKUP_FILENAME || ! -f $BACKUP_FILENAME ]]; then
				$ECHO "Invalid backup file to restore"
			else
				WPCHECK=$($EE site info $SITENAME | $GREP ^Nginx | $GREP wp | $WC -l)
                		MYSQLCHECK=$($EE site info $SITENAME | $GREP ^Nginx | $GREP mysql | $WC -l)
				if [[ $WPCHECK -eq 1 ]] || [[ $MYSQLCHECK -eq 1 ]]; then
	                		WPDBNAME=$($EE site info $SITENAME | $GREP DB_NAME | $CUT -d" " -f 2)
	                        	WPDBUSER=$($EE site info $SITENAME | $GREP DB_USER | $CUT -d" " -f 2)
	                        	WPDBPASS=$($EE site info $SITENAME | $GREP DB_PASS | $CUT -d" " -f 2)
	                        fi
				$ECHO -n "Restoring website folder... "
				$TAR -xzf $BACKUP_FILENAME -C $BASE_FOLDER
				$ECHO "[Done]"
				if [[ $WPCHECK -eq 1 ]] || [[ $MYSQLCHECK -eq 1 ]]; then
					$ECHO -n "Restoring database... "
					$MYSQL -u$WPDBUSER -p$WPDBPASS $WPDBNAME < $BASE_FOLDER/$WPDBNAME-dump.sql
					$ECHO "[Done]"
					$ECHO -n "Cleaning up... "
					$RM $BASE_FOLDER/$WPDBNAME-dump.sql
					$ECHO "[Done]"
				fi
			fi
		fi
	fi
else
	$ECHO "Unknown action"
fi
