#!/bin/bash
ECHO=/bin/echo
EE=/usr/local/bin/ee
GREP=/bin/grep
CUT=/usr/bin/cut
MKDIR=/bin/mkdir
CAT=/bin/cat
DATE=/bin/date
TAR=/bin/tar
RM=/bin/rm
LS=/bin/ls
SED=/bin/sed
MYSQLDUMP=/usr/bin/mysqldump
MYSQL=/usr/bin/mysql

if [ "$#" -le 1 ];then
	$ECHO "Usage: $0 <backup/restore> <sitename> [option]"
elif [ "$1" == "backup" ];then
	SITENAME=$2
	BASE_FOLDER=$($EE site info $SITENAME | $GREP Webroot | $CUT -d" " -f2)
	if [ -z "$BASE_FOLDER" ]; then
		$ECHO "Website not found"
	else
		WPDBHOST=$($CAT $BASE_FOLDER/wp-config.php | $GREP DB_HOST | $CUT -d \' -f 4)
		WPDBNAME=$($CAT $BASE_FOLDER/wp-config.php | $GREP DB_NAME | $CUT -d \' -f 4)
		WPDBUSER=$($CAT $BASE_FOLDER/wp-config.php | $GREP DB_USER | $CUT -d \' -f 4)
		WPDBPASS=$($CAT $BASE_FOLDER/wp-config.php | $GREP DB_PASSWORD | $CUT -d \' -f 4)
		if [ ! -d "$BASE_FOLDER/site-backup" ];then
			$MKDIR $BASE_FOLDER/site-backup
		fi
		$ECHO -n "Dumping database... "
		$MYSQLDUMP --single-transaction -h$WPDBHOST -u$WPDBUSER -p$WPDBPASS $WPDBNAME > $BASE_FOLDER/$WPDBNAME-dump.sql
		$ECHO "[Done]"
		BACKUP_FILENAME=$($DATE +"backup-$SITENAME-%Y%m%d-%H%M.tar.gz")
		$ECHO -n "Archiving website folder... "
		$TAR -czf $BASE_FOLDER/site-backup/$BACKUP_FILENAME -C $BASE_FOLDER htdocs $WPDBNAME-dump.sql
		$ECHO "[Done]"
		$ECHO -n "Cleaning up... "
		$RM $BASE_FOLDER/$WPDBNAME-dump.sql
		$ECHO "[Done]"
	fi
elif [ "$1" == "restore" ];then
	SITENAME=$2
	BASE_FOLDER=$($EE site info $SITENAME | $GREP Webroot | $CUT -d" " -f2)
	if [ -z "$BASE_FOLDER" ]; then
		$ECHO "Website not found"
	else
		if [ -z "$3" ];then
			if [[ ! -d "$BASE_FOLDER/site-backup" || -z $(ls $BASE_FOLDER/site-backup) ]]; then
				$ECHO "No backup found"
			else
				$ECHO "Select which backup to restore:"
				$LS $BASE_FOLDER/site-backup | $SED 's/.tar.gz//'
			fi
		else
			BACKUP_FILENAME=$BASE_FOLDER/site-backup/$3.tar.gz
			if [[ ! -r $BACKUP_FILENAME || ! -f $BACKUP_FILENAME ]]; then
				$ECHO "Invalid backup file to restore"
			else
				WPDBHOST=$($CAT $BASE_FOLDER/wp-config.php | $GREP DB_HOST | $CUT -d \' -f 4)
				WPDBNAME=$($CAT $BASE_FOLDER/wp-config.php | $GREP DB_NAME | $CUT -d \' -f 4)
				WPDBUSER=$($CAT $BASE_FOLDER/wp-config.php | $GREP DB_USER | $CUT -d \' -f 4)
				WPDBPASS=$($CAT $BASE_FOLDER/wp-config.php | $GREP DB_PASSWORD | $CUT -d \' -f 4)
				$ECHO -n "Restoring website folder... "
				$TAR -xzf $BACKUP_FILENAME -C $BASE_FOLDER
				$ECHO "[Done]"
				$ECHO -n "Restoring database... "
				$MYSQL -h$WPDBHOST -u$WPDBUSER -p$WPDBPASS $WPDBNAME < $BASE_FOLDER/$WPDBNAME-dump.sql
				$ECHO "[Done]"
				$ECHO -n "Cleaning up... "
				$RM $BASE_FOLDER/$WPDBNAME-dump.sql
				$ECHO "[Done]"
			fi
		fi
	fi
else
	$ECHO "Unknown action"
fi
