#!/bin/bash
ECHO=/bin/echo
EE=/usr/local/bin/ee
GREP=/bin/grep
CUT=/usr/bin/cut
MKDIR=/bin/mkdir
CAT=/bin/cat
DATE=/bin/date
TAR=/bin/tar
RM=/bin/rm
LS=/bin/ls
MV=/bin/mv
SED=/bin/sed
MYSQLDUMP=/usr/bin/mysqldump
MYSQL=/usr/bin/mysql
WC=/usr/bin/wc

if [ "$#" -le 1 ];then
	$ECHO "Usage: $0 <backup/restore> <sitename> [option]"
elif [ "$1" == "backup" ];then
	SITENAME=$2
	BASE_FOLDER=$($EE site info $SITENAME | $GREP Webroot | $CUT -d" " -f2)
	if [ -z "$BASE_FOLDER" ]; then
		$ECHO "Website not found"
	else
		BACKUP_FILENAME=$($DATE +"clone-$SITENAME-%Y%m%d-%H%M.tar.gz")
		WPCHECK=$($EE site info $SITENAME | $GREP ^Nginx | $GREP wp | $WC -l)
		MYSQLCHECK=$($EE site info $SITENAME | $GREP ^Nginx | $GREP mysql | $WC -l)
		if [[ $WPCHECK -eq 1 ]] || [[ $MYSQLCHECK -eq 1 ]]; then
			WPDBNAME=$($EE site info $SITENAME | $GREP DB_NAME | $CUT -d" " -f 2)
			WPDBUSER=$($EE site info $SITENAME | $GREP DB_USER | $CUT -d" " -f 2)
			WPDBPASS=$($EE site info $SITENAME | $GREP DB_PASS | $CUT -d" " -f 2)
			$ECHO -n "Dumping database... "
			$MYSQLDUMP --single-transaction -u$WPDBUSER -p$WPDBPASS $WPDBNAME > $BASE_FOLDER/db-dump.sql
			$ECHO "[Done]"
			if [[ $WPCHECK -eq 1 ]]; then
				$ECHO -n "Archiving website folder... "
				$TAR -czhf $BACKUP_FILENAME -C $BASE_FOLDER htdocs db-dump.sql wp-config.php
				$ECHO "[Done]"
			else
				$ECHO -n "Archiving website folder... "
				$TAR -czhf $BACKUP_FILENAME -C $BASE_FOLDER htdocs db-dump.sql
				$ECHO "[Done]"
			fi
			$ECHO -n "Cleaning up... "
			$RM $BASE_FOLDER/db-dump.sql
			$ECHO "[Done]"
		else
			$ECHO -n "Archiving website folder... "
			$TAR -czhf $BACKUP_FILENAME -C $BASE_FOLDER htdocs
			$ECHO "[Done]"
		fi
	fi
elif [ "$1" == "restore" ];then
	SITENAME=$2
	BASE_FOLDER=$($EE site info $SITENAME | $GREP Webroot | $CUT -d" " -f2)
	if [ -z "$BASE_FOLDER" ]; then
		$ECHO "Website not found"
	else
		if [ -z "$3" ];then
			$ECHO "Usage: $0 restore <sitename> <clone_archive>"
		else
			BACKUP_FILENAME=$3
			if [[ ! -r $BACKUP_FILENAME || ! -f $BACKUP_FILENAME ]]; then
				$ECHO "Invalid clone archive file to restore"
			else
				WPCHECK=$($EE site info $SITENAME | $GREP ^Nginx | $GREP wp | $WC -l)
				MYSQLCHECK=$($EE site info $SITENAME | $GREP ^Nginx | $GREP mysql | $WC -l)
				if [[ $WPCHECK -eq 1 ]] || [[ $MYSQLCHECK -eq 1 ]]; then
					WPDBNAME=$($EE site info $SITENAME | $GREP DB_NAME | $CUT -d" " -f 2)
                        		WPDBUSER=$($EE site info $SITENAME | $GREP DB_USER | $CUT -d" " -f 2)
                        		WPDBPASS=$($EE site info $SITENAME | $GREP DB_PASS | $CUT -d" " -f 2)
				fi
				$ECHO -n "Restoring website folder... "
				$TAR -xzf $BACKUP_FILENAME -C $BASE_FOLDER
				if [[ -r $BASE_FOLDER/htdocs/wp-config.php || -f $BASE_FOLDER/htdocs/wp-config.php ]]; then
					$MV $BASE_FOLDER/htdocs/wp-config.php $BASE_FOLDER/wp-config.php
				fi
				if [[ -w $BASE_FOLDER/wp-config.php || -f $BASE_FOLDER/wp-config.php ]]; then
					$SED -i '/DB_NAME/ s/\w\+'\'')/'$WPDBNAME\'')/' "$BASE_FOLDER/wp-config.php"
					$SED -i '/DB_USER/ s/\w\+'\'')/'$WPDBUSER\'')/' "$BASE_FOLDER/wp-config.php"
					$SED -i '/DB_PASSWORD/ s/\w\+'\'')/'$WPDBPASS\'')/' "$BASE_FOLDER/wp-config.php"
                                fi
				if [[ -w $BASE_FOLDER/htdocs/configuration.php || -f $BASE_FOLDER/htdocs/configuration.php ]]; then
                                        $SED -i '/\$db =/ s/\w\+'\'';/'$WPDBNAME\'';/' "$BASE_FOLDER/htdocs/configuration.php"
                                        $SED -i '/\$user =/ s/\w\+'\'';/'$WPDBUSER\'';/' "$BASE_FOLDER/htdocs/configuration.php"
                                        $SED -i '/\$password/ s/\w\+'\'';/'$WPDBPASS\'';/' "$BASE_FOLDER/htdocs/configuration.php"
                                fi
				$ECHO "[Done]"
				if [[ $WPCHECK -eq 1 ]] || [[ $MYSQLCHECK -eq 1 ]]; then
					$ECHO -n "Restoring database... You may need to update db settings in config file manually "
					$MYSQL -u$WPDBUSER -p$WPDBPASS $WPDBNAME < $BASE_FOLDER/db-dump.sql
					$ECHO "[Done]"
					$ECHO -n "Cleaning up... "
					$RM $BASE_FOLDER/db-dump.sql
					$ECHO "[Done]"
				fi
			fi
		fi
	fi
else
	$ECHO "Unknown action"
fi
