#!/bin/bash
ECHO=/bin/echo
EE=/usr/local/bin/ee
GREP=/bin/grep
CUT=/usr/bin/cut
RSYNC=/usr/bin/rsync
MYSQLDUMP=/usr/bin/mysqldump
if [ "$#" -ne 1 ];then
	$ECHO "Usage: $0 <sitename>"
else
	website=$1
	dbname=$($EE site info $website | $GREP DB_NAME | $CUT -d" " -f2)
	if [ -z "$dbname" ]; then
		$ECHO "Website not found"
	else
		ssh livedemo "cd /root/thangkm/; eec backup $website"
		$RSYNC -azL --delete-after --log-file=/root/thangkm/sync.log /var/www/$website/htdocs livedemo:/var/www/$website/
		$MYSQLDUMP --single-transaction $dbname > /root/thangkm/$dbname.bsql
		$RSYNC -azL --delete-after --log-file=/root/thangkm/sync.log /root/thangkm/$dbname.bsql livedemo:/root/thangkm/
		ssh livedemo "mysql $dbname < /root/thangkm/$dbname.bsql" 
		ssh livedemo "ee clean --all"
	fi
fi
